from docsie_universal_importer.providers.base.urls import default_urlpatterns

from .import_provider import GoogleCloudStorageOAuth2Provider

urlpatterns = default_urlpatterns(GoogleCloudStorageOAuth2Provider)
