# Generated by Django 2.2.2 on 2021-10-19 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docsie_universal_importer', '0001_connector_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectortoken',
            name='user',
            field=models.ForeignKey(help_text='Token owner', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
